sequenceDiagram
    actor User as Пользователь
    participant ResourceClient as Клиент<br/>объекта доступа
    participant VerificationClient as Клиент<br/>верификации
    participant VerificationAgent as Агент сервиса<br/>верификации
    participant VerificationService as Сервис<br/>верификации
    participant ResourceService as Сервис<br/>объекта доступа

    activate User
    User->>+ResourceClient: Переход на страницу защищенного ресурса
    ResourceClient->>+ResourceService: Запрос ресурса

    Note over User,ResourceService: Инициализация сессии верификации
    ResourceService->>+VerificationAgent: Запрос на инициализацию сессии
    VerificationAgent->>+VerificationService: Запрос на инициализацию сессии
    VerificationService->>VerificationService: Создание записи сессии
    VerificationService-->>-VerificationAgent: sid
    VerificationAgent->>VerificationAgent: Создание записи сессии
    VerificationAgent-->>-ResourceService: sid
    ResourceService-->>-ResourceClient: Ответ с sid и URL клиента верификации

    Note over User,ResourceService: Перенаправление пользователя на клиент верификации
    ResourceClient-->>-User: Перенаправление с sid
    User->>+VerificationClient: Запрос на верификацию с sid

    Note over User,ResourceService: Получение параметров протокола
    VerificationClient->>+VerificationAgent: Запрос параметров протокола
    VerificationAgent->>+VerificationService: Запрос параметров протокола
    VerificationService-->>-VerificationAgent: Параметры протокола
    VerificationAgent->>VerificationAgent: Сохранение параметров протокола
    VerificationAgent-->>-VerificationClient: Параметры протокола

    Note over User,ResourceService: Генерация открытого ключа
    VerificationClient->>VerificationClient: Генерация долей sk_c, pk_c
    VerificationClient->>+VerificationAgent: Передача pk_c
    VerificationAgent->>VerificationAgent: Генерация долей sk_a, pk_a
    VerificationAgent->>VerificationAgent: Объединение pk
    VerificationAgent-->>-VerificationClient: Передача pk_a
    VerificationClient->>VerificationClient: Объединение pk

    Note over User,ResourceService: Генерация ключа релинеаризации (раунд 1)
    VerificationClient->>VerificationClient: Генерация ephSk_c, rlk_c⁽¹⁾
    VerificationClient->>+VerificationAgent: Передача rlk_c⁽¹⁾
    VerificationAgent->>VerificationAgent: Генерация ephSk_a, rlk_a⁽¹⁾
    VerificationAgent->>VerificationAgent: Объединение rlk⁽¹⁾_agg
    VerificationAgent-->>-VerificationClient: Передача rlk_a⁽¹⁾
    VerificationClient->>VerificationClient: Объединение rlk⁽¹⁾_agg

    Note over User,ResourceService: Генерация ключа релинеаризации (раунд 2)
    VerificationClient->>VerificationClient: Генерация rlk_c⁽²⁾
    VerificationClient->>+VerificationAgent: Передача rlk_c⁽²⁾
    VerificationAgent->>VerificationAgent: Генерация rlk_a⁽²⁾
    VerificationAgent->>VerificationAgent: Объединение rlk
    VerificationAgent-->>-VerificationClient: Подтверждение генерации rlk

    Note over User,ResourceService: Генерация ключей вращения
    VerificationClient->>VerificationClient: Генерация gks_master_c
    VerificationClient->>+VerificationAgent: Передача gks_master_c
    VerificationAgent->>VerificationAgent: Генерация gks_master_a
    VerificationAgent->>VerificationAgent: Объединение gks_master
    VerificationAgent->>+VerificationService: Передача rlk, gks_master
    VerificationService->>VerificationService: Иерархический вывод gks из gks_master
    VerificationService-->>-VerificationAgent: Подтверждение установки ключей
    VerificationAgent-->>-VerificationClient: Подтверждение генерации gks

    Note over User,ResourceService: Захват и шифрование изображения
    User->>VerificationClient: Предоставление изображения
    VerificationClient->>VerificationClient: Шифрование изображения

    Note over User,ResourceService: Инференс
    VerificationClient->>+VerificationAgent: Шифротекст изображения
    VerificationAgent->>+VerificationService: Шифротекст изображения
    VerificationService->>VerificationService: Инференс на зашифрованных данных
    VerificationService-->>-VerificationAgent: Шифротекст результата

    Note over User,ResourceService: Проверяемая расшифровка результата
    VerificationAgent->>VerificationAgent: Генерация проверочных значений
    VerificationAgent->>VerificationAgent: Создание аутентифицированного шифротекста
    VerificationAgent-->>VerificationClient: Аутентифицированный шифротекст
    VerificationClient->>VerificationClient: Частичная расшифровка (sk_c, noise flooding)
    VerificationClient->>+VerificationAgent: Частично расшифрованный шифротекст
    VerificationAgent->>VerificationAgent: Окончательная расшифровка (sk_a)
    VerificationAgent->>VerificationAgent: Проверка аутентичности
    VerificationAgent->>VerificationAgent: Вычисление вердикта верификации

    Note over User,ResourceService: Передача результата верификации
    VerificationAgent->>+ResourceService: Результат проверки и вердикт верификации
    ResourceService->>ResourceService: Сохранение результата верификации
    ResourceService-->>-VerificationAgent: Подтверждение
    VerificationAgent-->>-VerificationClient: Подтверждение завершения верификации
    VerificationClient-->>-User: Перенаправление на страницу ресурса
    User->>+ResourceClient: Возврат на страницу ресурса

    Note over User,ResourceService: Повторный запрос ресурса
    ResourceClient->>+ResourceService: Запрос ресурса
    alt Положительный вердикт верификации
        ResourceService-->>ResourceClient: Предоставление ресурса
        ResourceClient-->>User: Отображение ресурса
    else Отрицательный вердикт верификации
        ResourceService-->>ResourceClient: Отказ в доступе
        ResourceClient-->>User: Сообщение об отказе в доступе
    end
    deactivate ResourceService
    deactivate ResourceClient
    deactivate User
